# Defining the actions taking place before the commit
# GitGuardian checks if there are any passwords, access keys, etc. before pushing the commit
repos:
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.13.6
    hooks:
      - id: ggshield-push
        language_version: python3
        stages: [push]
